<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="base" nsURI="http://www.eltesoft.hu/modelexecution/m2m/metamodel/base"
    nsPrefix="hu.eltesoft.modelexecution.m2m.metamodel.base">
  <eClassifiers xsi:type="ecore:EClass" name="TranslationObject" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelRoot" abstract="true" interface="true"
      eSuperTypes="#//Named"/>
  <eClassifiers xsi:type="ecore:EClass" name="Named" abstract="true" interface="true"
      eSuperTypes="#//TranslationObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" lowerBound="1"
        eType="#//NamedReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Referenced" abstract="true" eSuperTypes="#//TranslationObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" lowerBound="1"
        eType="#//Reference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="NamedReference" instanceClassName="hu.eltesoft.modelexecution.m2m.metamodel.base.NamedReference"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Reference" instanceClassName="hu.eltesoft.modelexecution.m2t.smap.emf.Reference"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveTypes">
    <eLiterals name="Integer" literal="Integer"/>
    <eLiterals name="Boolean" value="1"/>
    <eLiterals name="String" value="2" literal="String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//Named"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PrimitiveTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="in"/>
    <eLiterals name="out" value="1"/>
    <eLiterals name="inout" value="2" literal=""/>
    <eLiterals name="return" value="3"/>
  </eClassifiers>
</ecore:EPackage>
