<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="behavior" nsURI="http://www.eltesoft.hu/modelexecution/m2m/metamodel/behavior"
    nsPrefix="hu.eltesoft.modelexecution.m2m.metamodel.behavior">
  <eClassifiers xsi:type="ecore:EClass" name="BhBehavior" eSuperTypes="base.ecore#//ModelRoot base.ecore#//Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containerClass" lowerBound="1"
        eType="ecore:EDataType base.ecore#//NamedReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alfResult" lowerBound="1"
        eType="#//AlfAnalyzerResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//BhParameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="ecore:EClass base.ecore#//FullType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlfAnalyzerResult" instanceClassName="hu.eltesoft.modelexecution.uml.alf.AlfAnalyzerResult"/>
  <eClassifiers xsi:type="ecore:EClass" name="BhParameter" eSuperTypes="base.ecore#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass base.ecore#//FullType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="ecore:EEnum base.ecore#//Direction"/>
  </eClassifiers>
</ecore:EPackage>
