<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="classdef" nsURI="http://www.eltesoft.hu/modelexecution/m2m/metamodel/classdef"
    nsPrefix="hu.eltesoft.modelexecution.m2m.metamodel.classdef">
  <eClassifiers xsi:type="ecore:EClass" name="ClClass" eSuperTypes="base.ecore#//ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="region" eType="ecore:EDataType base.ecore#//NamedReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inheritedRegion" eType="ecore:EDataType base.ecore#//NamedReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" ordered="false"
        upperBound="-1" eType="#//ClOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receptions" ordered="false"
        upperBound="-1" eType="#//ClReception"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" ordered="false"
        upperBound="-1" eType="#//ClAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritedAttributes" ordered="false"
        upperBound="-1" eType="#//ClInheritedAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" ordered="false"
        upperBound="-1" eType="#//ClAssociation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parents" ordered="false"
        upperBound="-1" eType="ecore:EDataType base.ecore#//NamedReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ctorRecords" upperBound="-1"
        eType="#//ClCtorRecord"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClClassSpec" eSuperTypes="base.ecore#//ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" ordered="false"
        upperBound="-1" eType="#//ClOperationSpec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receptions" ordered="false"
        upperBound="-1" eType="#//ClReceptionSpec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" ordered="false"
        upperBound="-1" eType="#//ClAttributeSpec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" ordered="false"
        upperBound="-1" eType="#//ClAssociation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasStateMachine" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parents" ordered="false"
        upperBound="-1" eType="ecore:EDataType base.ecore#//NamedReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClClassCommon" abstract="true" eSuperTypes="base.ecore#//ModelRoot"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClOperation" eSuperTypes="#//ClOperationSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="ecore:EDataType base.ecore#//NamedReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClOperationSpec" eSuperTypes="base.ecore#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="ecore:EClass base.ecore#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass base.ecore#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClReception" eSuperTypes="#//ClReceptionSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signal" lowerBound="1"
        eType="ecore:EDataType base.ecore#//NamedReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClReceptionSpec" eSuperTypes="base.ecore#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ClReceptionParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClReceptionParameter" eSuperTypes="base.ecore#//Named base.ecore#//Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass base.ecore#//PrimitiveType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClAttribute" eSuperTypes="#//ClAttributeSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClAttributeSpec" eSuperTypes="base.ecore#//Named base.ecore#//Typed"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClInheritedAttribute" eSuperTypes="#//ClAttributeSpec #//Inherited"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClAssociation" eSuperTypes="base.ecore#//Named base.ecore#//Typed"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClCtorRecord" eSuperTypes="base.ecore#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedArgs" upperBound="-1"
        eType="ecore:EClass base.ecore#//NameWrapper"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inherited" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parent" lowerBound="1"
        eType="ecore:EDataType base.ecore#//NamedReference"/>
  </eClassifiers>
</ecore:EPackage>
