<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="behavior" nsURI="http://www.eltesoft.hu/modelexecution/m2m/behavior"
    nsPrefix="hu.eltesoft.modelexecution.m2m.metamodel.behavior">
  <eClassifiers xsi:type="ecore:EClass" name="BhBehavior" eSuperTypes="base.ecore#//Named base.ecore#//Identified">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alfCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
