<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="classdef" nsURI="http://www.eltesoft.hu/modelexecution/m2m/classdef"
    nsPrefix="hu.eltesoft.modelexecution.m2m.metamodel.classdef">
  <eClassifiers xsi:type="ecore:EClass" name="ClClass" eSuperTypes="base.ecore#//Named base.ecore#//Identified">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//ClOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receptions" upperBound="-1"
        eType="#//ClSignal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClOperation" eSuperTypes="base.ecore#//Named base.ecore#//Identified">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClReception" eSuperTypes="base.ecore#//Named base.ecore#//Identified">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
        eType="#//ClSignal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClSignal" eSuperTypes="base.ecore#//Named base.ecore#//Identified"/>
</ecore:EPackage>
