<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="event" nsURI="http://www.eltesoft.hu/modelexecution/m2m/metamodel/event"
    nsPrefix="hu.eltesoft.modelexecution.m2m.metamodel.event">
  <eClassifiers xsi:type="ecore:EClass" name="EvEvent" eSuperTypes="base.ecore#//ModelRootType base.ecore#//Named"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvSignalEvent" eSuperTypes="#//EvEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
        eType="#//EvSignal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvSignal" eSuperTypes="base.ecore#//Named"/>
</ecore:EPackage>
