<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="region" nsURI="http://www.eltesoft.hu/modelexecution/m2m/metamodel/region"
    nsPrefix="hu.eltesoft.modelexecution.m2m.metamodel.region">
  <eClassifiers xsi:type="ecore:EClass" name="RgRegion" eSuperTypes="base.ecore#//ModelRootType base.ecore#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containingClass" lowerBound="1"
        eType="#//RgClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial" lowerBound="1"
        eType="#//RgState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialEffect" eType="#//RgBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
        upperBound="-1" eType="#//RgState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RgClass" eSuperTypes="base.ecore#//Named"/>
  <eClassifiers xsi:type="ecore:EClass" name="RgState" eSuperTypes="base.ecore#//Named base.ecore#//Referenced">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="#//RgBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exit" eType="#//RgBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" lowerBound="1"
        upperBound="-1" eType="#//RgTransition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RgTransition" eSuperTypes="base.ecore#//Referenced">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="#//RgEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effect" eType="#//RgBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//RgState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RgEvent" eSuperTypes="base.ecore#//Named"/>
  <eClassifiers xsi:type="ecore:EClass" name="RgBehavior" eSuperTypes="base.ecore#//Named"/>
</ecore:EPackage>
